import "./globals.css";

export const metadata = {
  title: "Placio for Business",
  description: "Generated by Placio dev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-primary">{children}</body>
    </html>
  );
}
