#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi

. "$(dirname "$0")/_/husky.sh"

yarn format
# yarn prettier
yarn lint-staged --no-stash
yarn build